### ISSUE TITLE
Minified code?

### ISSUE THREAD

**Issue by ghost** [Gaafar/deppie#1]
How are you handling minified code if you're are converting the invoking function to a string and parsing its arguments?

**Comment by Gaafar** [comment]
It's because of destructuring, a minfier may change the name of function parameters, but is not supposed to alter the names of object properties.

so a minifier can change `function(arg1, arg2)` to `function(a, b)`
but it should not change the object properties in `function({ arg1, arg2 })`

**Comment by ghost** [comment]
Does this hold true during transpilation down to es5?

**Comment by Gaafar** [comment]
Yes, object property names should not be changed during transpilation or minification as they will break any code depending on them. In this example the transpiled code uses the same property names https://babeljs.io/repl/#?evaluate=true&lineWrap=false&presets=es2015&experimental=false&loose=false&spec=false&code=module.exports%20%3D%20(%7B%20routes%2C%20config%20%7D)%20%3D%3E%20%7B%0A%20%20%20%20const%20app%20%3D%20express()%3B%0A%0A%20%20%20%20%2F%2F%20Add%20routes%0A%20%20%20%20_.each(routes%2C%20(%7B%20method%2C%20pattern%2C%20middleware%20%3D%20%5B%5D%2C%20handler%20%7D)%20%3D%3E%0A%20%20%20%20app%5Bmethod%5D(pattern%2C%20%5B...middleware%2C%20handler%5D))%3B%0A%0A%20%20%20%20app.listen(config.port)%3B%0A%20%20%20%20console.log(%60listening%20on%20port%20%24%7Bconfig.port%7D%60)%3B%0A%7D%3B 

However the deppie currently doesn't support transpilation to es5, it has to run in es6
